version: '3.8'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - ./services/web/:/usr/src/app/
    expose:
      - 5000
    env_file:
      - ./.env.dev

    networks:
      net:
        ipv4_address: 10.5.0.4

    depends_on:
      - db


  nginx:
    build: ./services/nginx
    ports:
      - "1337:80"

    networks:
      net:
        ipv4_address: 10.5.0.5

    depends_on:
      - web

  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - /services/postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: 'pg'
      POSTGRES_PASSWORD: 'pg'
      POSTGRES_DB: 'SW_DB'

    ports:
      - "5432:5432"
    restart: always

    networks:
      net:
        ipv4_address: 10.5.0.2

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "pg@rpz.ru"
      PGADMIN_DEFAULT_PASSWORD: "pg"
    ports:
      - "5050:81"
    restart: unless-stopped
    networks:
      net:
        ipv4_address: 10.5.0.3

volumes:
  postgres_data:

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16




