version: '3.8'

services:
  web:
    build: ./services/web
    command: python project/app.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5002:5000
    env_file:
      - ./.env.dev